definitions:
  dtos.UserCreate:
    properties:
      mobile_number:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - mobile_number
    - password
    - username
    type: object
  dtos.UserResponse:
    properties:
      firstname:
        type: string
      id:
        type: integer
      lastname:
        type: string
      mobile_number:
        type: string
      username:
        type: string
    type: object
  handlers.OtpDto:
    properties:
      mobile_number:
        type: string
    required:
    - mobile_number
    type: object
  responses.Response:
    properties:
      error:
        type: string
      message:
        type: string
      result: {}
      status:
        type: boolean
      statusCode:
        type: integer
      validationError:
        items:
          $ref: '#/definitions/validations.ValidationError'
        type: array
    type: object
  validations.ValidationError:
    properties:
      field:
        type: string
      param:
        type: string
      tag:
        type: string
    type: object
info:
  contact: {}
paths:
  /user/get/otp:
    post:
      consumes:
      - application/json
      description: get otp by valid mobile_number
      parameters:
      - description: body for get mobile_number
        in: body
        name: OtpDto
        required: true
        schema:
          $ref: '#/definitions/handlers.OtpDto'
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            allOf:
            - $ref: '#/definitions/responses.Response'
            - properties:
                result:
                  type: string
              type: object
        "400":
          description: Validation Error
          schema:
            $ref: '#/definitions/responses.Response'
        "503":
          description: Redis Error
          schema:
            $ref: '#/definitions/responses.Response'
      summary: Get Otp
      tags:
      - User
  /user/new:
    post:
      consumes:
      - application/json
      description: make new user with username and password and mobile_number and
        also the otp has gotten by mobile_number
      parameters:
      - description: body for create user
        in: body
        name: UserCreate
        required: true
        schema:
          $ref: '#/definitions/dtos.UserCreate'
      - description: the otp has been gotten for the mobile_number
        in: query
        name: otp
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            allOf:
            - $ref: '#/definitions/responses.Response'
            - properties:
                result:
                  $ref: '#/definitions/dtos.UserResponse'
              type: object
        "400":
          description: Validation Error
          schema:
            $ref: '#/definitions/responses.Response'
        "406":
          description: Error
          schema:
            $ref: '#/definitions/responses.Response'
      summary: Make New User
      tags:
      - User
swagger: "2.0"
