version: '3.9'

services:
  postgres:
    container_name: twitter_postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=arash2007mahdavi
      - POSTGRES_PASSWORD=@rash2007
      - POSTGRES_DB=twitterDB
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - twitter_network
    restart: always
  pgadmin:
    container_name: twitter_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: arashmahdavi2007@gmail.com
      PGADMIN_DEFAULT_PASSWORD: arash2007
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "8080:80"
    networks:
      - twitter_network
    restart: unless-stopped
    depends_on:
    - postgres
  redis:
    container_name: twitter_redis
    image: redis:latest
    command: ["redis-server", "/etc/redis/redis.conf"]
    volumes:
      - ./redis/redis.conf:/etc/redis/redis.conf
    ports:
      - "6379:6379"
    networks:
      - twitter_network
  prometheus:
    image: prom/prometheus
    container_name: twitter_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml


volumes:
  postgres:
  pgadmin:
  redis:
  prometheus:

networks:
  twitter_network:
    driver: bridge